name: kiatsu
description: An application for meteoropathy
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Androidのバージョン指定。前者がVersionNameで後者がVersionCode
version: 1.0.7+746

environment:
  sdk: ">=2.12.0 <3.0.0"

module:
  androidX: true

dependencies:
  app_tracking_transparency: ^2.0.2+1
  cloud_firestore: ^3.1.0
  cloud_functions: ^3.2.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  dart_jsonwebtoken: ^2.4.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_crashlytics: ^2.2.0
  firebase_dynamic_links: ^4.0.2
  flutter:
    sdk: flutter
  flutter_device_type: ^0.4.0
  flutter_dotenv: ^5.0.2
  flutter_flavor: ^3.0.3
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.9.0
  flutter_line_sdk: ^2.0.0
  flutter_native_splash: ^2.0.5
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git
      publish_to: none
  flutter_riverpod: ^1.0.0
  flutter_screenutil: ^5.0.1
  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^1.0.0
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  getwidget: ^2.0.5
  google_mobile_ads: ^1.0.0
  google_sign_in: ^5.0.7
  hooks_riverpod: ^1.0.3
  http: ^0.13.3
  in_app_purchase: ^3.0.1
  in_app_purchase_android: ^0.2.2+1
  intl: ^0.17.0
  is_first_run: ^1.0.0
  json_annotation: ^4.4.0
  lottie: ^1.2.1
  meta: ^1.7.0
  modal_bottom_sheet: ^2.0.0
  onboarding_overlay: ^3.0.0
  package_info: ^2.0.0
  pal_widgets: ^0.2.0
  permission_handler: ^9.2.0
  provider: ^6.0.0
  purchases_flutter: ^3.4.3
  rxdart: ^0.27.3
  scaled_list: ^2.0.0
  settings_ui:
    git:
      url: https://github.com/higedamc/flutter-settings-ui.git
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sign_in_with_apple: ^3.0.0
  simple_logger: ^1.9.0
  smooth_page_indicator: ^1.0.0+2
  social_auth_buttons: ^2.0.0-nullsafety.1
  splash_screen_view: ^3.0.0
  subscription_holder: ^2.1.1
  the_apple_sign_in: ^1.1.1
  timeago: ^3.0.2
  tutorial_coach_mark: ^1.2.1
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.0
  wiredash: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  pedantic_mono: ^1.17.0
  twitter_login: ^4.2.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kiatsu_logo_invert.jpg"

  flutter_gen_runner:
    output: lib/gen/
    integrations:
      flutter_svg: true
    #   flare_flutter: false
    #   rive: false
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/kiatsu_logo_invert.jpg
    - assets/images/face.png
    - assets/images/line.png
    - assets/images/model.jpg
    - assets/json/arrow_down_bounce.json
    - assets/
    - .env
# To add assets to your application, add an assets section, like this:
#   assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
