// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_OPTIONS_API_KEY_ANDROID'] ?? '',
    appId: dotenv.env['FIREBASE_OPTIONS_APP_ID_ANDROID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_OPTIONS_MESSAGING_SENDER_ID'] ?? '',
    projectId: 'kiatsu-81a16',
    databaseURL: dotenv.env['FIREBASE_OPTIONS_DATABASE_URL'] ?? '',
    storageBucket: dotenv.env['FIREBASE_OPTIONS_STORAGE_BUCKET'] ?? '',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_OPTIONS_API_KEY_IOS'] ?? '',
    appId: dotenv.env['FIREBASE_OPTIONS_APP_ID_IOS'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_OPTIONS_MESSAGING_SENDER_ID'] ?? '',
    projectId: 'kiatsu-81a16',
    databaseURL: dotenv.env['FIREBASE_OPTIONS_DATABASE_URL'] ?? '',
    storageBucket: dotenv.env['FIREBASE_OPTIONS_STORAGE_BUCKET'] ?? '',
    androidClientId: dotenv.env['FIREBASE_OPTIONS_CLIENT_ID_ANDROID'] ?? '',
    iosClientId: dotenv.env['FIREBASE_OPTIONS_CLIENT_ID_IOS'] ?? '',
    iosBundleId: 'com.kiatsu.app',
  );
}
