# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :testf do
    # add actions here: https://docs.fastlane.tools/actions
    # disable auto signing
    # disable_automatic_code_signing(path: "Runner.xcodeproj")
    # sync_code_signing(type: "appstore")
    increment_version_number(xcodeproj: "Runner.xcodeproj")
    match(app_identifier: "com.kiatsu.app-prod", type: "appstore", readonly: is_ci)
    # build_app(
    #   workspace: "Runner.xcworkspace",
    #   scheme: "Runner",
    #   export_options: {
    #     method: "app-store"
    #   },
    #   skip_build_archive: true,
    #   archive_path: "../build/ios/archive/Runner.xcarchive",
    # )
    
    # build for TestFlight
    gym(scheme: "Runner",
        workspace: "Runner.xcworkspace",
        export_method: "app-store")
    upload_to_testflight
    slack(
      message: "App is released!",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end
