# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "The lane for distributing Flutter app for iOS"
  lane :kiatsu_test do
    build_ios_app(
      scheme: "Runner",
      archive_path: "./build/Runner.xcarchive",
      # build_type: "Release",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE"],
        },
      },
      output_directory: "./build/Runner",
    )
    firebase_app_distribution(
      app: ENV["APP_KEY"],
      groups: "me",
      firebase_cli_path: "/Users/jackstash/.volta/bin/firebase",
      ipa_path: "./build/Runner/Runner.ipa",
      release_notes_file: "/Users/jackstash/Pictures/work/kiatsu/release_notes.txt",
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
