# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "The lane for distributing Flutter app for iOS"
  lane :kiatsu_test do
    build_ios_app(
      scheme: "prod",
      # archive_path: "./build/Runner.xcarchive",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE_RELEASE"],
        },
      },
      output_directory: "./build/Runner",
    )
    # desc "Push a new release build to the TestFlight"
    # lane :beta do
    # increment_build_number(xcodeproj: "/Users/jackstash/Pictures/work/kiatsu/ios/Runner.xcodeproj")
    # match(type: "appstore")
    # cocoapods
    # build_app(
    #   workspace: "/Users/jackstash/Pictures/work/kiatsu/ios/Runner.xcworkspace",
    #   # scheme: "XXXXX_APPSTORE",
    # )
    # upload_to_testflight(
 # skip_waiting_for_build_processing: true,
      # )
    # end
    firebase_app_distribution(
      app: ENV["APP_KEY"],
      groups: "me",
      firebase_cli_path: "/Users/jackstash/.volta/bin/firebase",
      ipa_path: "./build/Runner/Runner.ipa",
      release_notes_file: "/Users/jackstash/Pictures/work/kiatsu/release_notes.txt",
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
