# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "fastlane"
gem 'dotenv-rails', groups: [:development, :test]

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
