# frozen_string_literal: true

source "https://rubygems.org"
gem "fastlane"
gem 'dotenv-rails', groups: [:development, :test]
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
