# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ forActions ]
  pull_request:
    branches: [ forActions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    runs-on: ubuntu-16.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2.3.3
    - uses: actions/checkout@v2
    # - name: set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: build release
    #   run: ./gradlew build
    - name: GET PGP RIGHT
      run: ./.github/scripts/decrypt_secret_ubuntu.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.0
      # with:
      #   flutter-version: '1.20.4'
    - run: flutter clean
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build appbundle -t lib/env/production.dart

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: build/app/outputs/apk/release/app-release.apk

  deploy_android:
    needs: [build]
    runs-on: ubuntu-16.04
    steps:

    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: android

    
    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: android/app-release.apk
